name: GameArena
main: me.devphp.ga.Core
authors: [Devphp]
version: 1.0.1.1
commands:
  arena:
    description: GameArena SimpleGame Arena
permissions:
  gamearena.creator:
    description: allows the creation of arena